//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<int> Department_Id { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
